/*Inserting the 40 seats that are on the restaurant's inside to the database,
two guests per movable table with a unique tableID to keep them apart*/
INSERT INTO Tables VALUES (1, 2);
INSERT INTO Tables VALUES (2, 2);
INSERT INTO Tables VALUES (3, 2);
INSERT INTO Tables VALUES (4, 2);
INSERT INTO Tables VALUES (5, 2);
INSERT INTO Tables VALUES (6, 2);
INSERT INTO Tables VALUES (7, 2);
INSERT INTO Tables VALUES (8, 2);
INSERT INTO Tables VALUES (9, 2);
INSERT INTO Tables VALUES (10, 2);
INSERT INTO Tables VALUES (11, 2);
INSERT INTO Tables VALUES (12, 2);
INSERT INTO Tables VALUES (13, 2);
INSERT INTO Tables VALUES (14, 2);
INSERT INTO Tables VALUES (15, 2);
INSERT INTO Tables VALUES (16, 2);
INSERT INTO Tables VALUES (17, 2);
INSERT INTO Tables VALUES (18, 2);
INSERT INTO Tables VALUES (19, 2);
INSERT INTO Tables VALUES (20, 2);

--Inserting all the allowed booking times for a specific date
--OBS! Remember when trigger is made: if someone is booking 21,
--only this timeslot will be booked, no other timeslots
/*Adding times until 22:30 since those will be booked by the last bookable time of 21:00.
The limit of bookingtimes is set in Available reservations(?)*/

INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '-1 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE, '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '1 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '2 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '3 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '4 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '5 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '6 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '7 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '8 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '9 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '10 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '11 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '12 days', '22:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '17:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '17:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '18:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '18:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '19:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '19:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '20:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '20:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '21:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '21:30:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '22:00:00');
INSERT INTO BookingTimes VALUES (CURRENT_DATE + INTERVAL '13 days', '22:30:00');

--Inserting bookings, each booking books 4 timeslots
INSERT INTO Bookings VALUES ('Ida', 'ida@live.com', '0761022440', 4, CURRENT_DATE, '17:00:00');
INSERT INTO Bookings VALUES ('Ida', 'ida@live.com', '0761022440', 4, CURRENT_DATE, '17:30:00');
INSERT INTO Bookings VALUES ('Ida', 'ida@live.com', '0761022440', 4, CURRENT_DATE, '18:00:00');
INSERT INTO Bookings VALUES ('Ida', 'ida@live.com', '0761022440', 4, CURRENT_DATE, '18:30:00');

INSERT INTO Bookings VALUES ('Lisa', 'lisa@live.com', '0761022442', 2, CURRENT_DATE, '17:30:00');
INSERT INTO Bookings VALUES ('Lisa', 'lisa@live.com', '0761022442', 2, CURRENT_DATE, '18:00:00');
INSERT INTO Bookings VALUES ('Lisa', 'lisa@live.com', '0761022442', 2, CURRENT_DATE, '18:30:00');
INSERT INTO Bookings VALUES ('Lisa', 'lisa@live.com', '0761022442', 2, CURRENT_DATE, '19:00:00');

INSERT INTO Bookings VALUES ('Astrid', 'astrid@live.com', '0761022441', 3, CURRENT_DATE, '18:00:00');

--Inserting bookings of the specific tables. When a booking is inserted
--for a specific start time, it also books all the timeslots for those tables
--two hours forward. (If a booking is done 17:00, the next booking can be done
--19:00) Will not need to do this once the trigger is created, since each insert on
--Bookings will trigger this
INSERT INTO BookedTables VALUES (1, CURRENT_DATE, '17:00:00', 'ida@live.com');
INSERT INTO BookedTables VALUES (1, CURRENT_DATE, '17:30:00', 'ida@live.com');
INSERT INTO BookedTables VALUES (1, CURRENT_DATE, '18:00:00', 'ida@live.com');
INSERT INTO BookedTables VALUES (1, CURRENT_DATE, '18:30:00', 'ida@live.com');

INSERT INTO BookedTables VALUES (2, CURRENT_DATE, '17:00:00', 'ida@live.com');
INSERT INTO BookedTables VALUES (2, CURRENT_DATE, '17:30:00', 'ida@live.com');
INSERT INTO BookedTables VALUES (2, CURRENT_DATE, '18:00:00', 'ida@live.com');
INSERT INTO BookedTables VALUES (2, CURRENT_DATE, '18:30:00', 'ida@live.com');


INSERT INTO BookedTables VALUES (4, CURRENT_DATE, '17:30:00', 'lisa@live.com');
INSERT INTO BookedTables VALUES (4, CURRENT_DATE, '18:00:00', 'lisa@live.com');
INSERT INTO BookedTables VALUES (4, CURRENT_DATE, '18:30:00', 'lisa@live.com');
INSERT INTO BookedTables VALUES (4, CURRENT_DATE, '19:00:00', 'lisa@live.com');

--INSERT INTO BookedTables VALUES (1, CURRENT_DATE, '17:30:00', 'lisa@live.com');


INSERT INTO BookingsView VALUES (CURRENT_DATE, '17:00:00', 1, 'dieter@live.com', 'Dieter',  0761022445, 2);
INSERT INTO BookingsView VALUES (CURRENT_DATE, '21:00:00', 1, 'elias@live', 'Elias',  0761099883, 2);